apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: epfl-project-rbac
  title: Project + RBAC (per-group role)
  description: Create Environment/Projects and RoleBindings for selected groups/roles
  tags: [namespace, project, rbac, environment, epfl]
spec:
  owner: assiga@epfl.ch
  type: service

  parameters:
    - title: Project Details
      required: [project, description, environment]
      properties:
        project:
          title: Project
          type: string
          description: K8s namespace/project name
        description:
          title: Description
          type: string
          description: Short description shown on the namespace
        environment:
          title: Environment
          type: string
          enum: ["dev","preprod","prod"]

    - title: Team
      required: [teams]
      properties:
        teams:
          title: Teams
          type: array
          description: Pick a group and one role for each row
          items:
            type: object
            required: [group, role]
            properties:
              group:
                title: Group
                type: string
                description: Identity provider group name
                # If you want a fixed dropdown like the mock, keep enum below.
                # Otherwise remove enum to allow free text or use OwnerPicker.
                enum: ["group-a","group-b","group-c"]
              role:
                title: Role
                type: string
                enum: ["edit","view","admin","custom"]
                default: "view"
                ui:widget: radio
          ui:options:
            orderable: false
            addable: true
            removable: true
          default:
            - { group: "group-a", role: "edit" }
            - { group: "group-b", role: "admin" }
            - { group: "group-c", role: "custom" }

  steps:
    - id: fetch
      name: Fetch skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          project: ${{ parameters.project }}
          description: ${{ parameters.description }}
          environment: ${{ parameters.environment }}
          teams: ${{ parameters.teams }}

    - id: mr
      name: Open GitLab Merge Request
      action: publish:gitlab:merge-request
      input:
        allowedHosts: ['gitlab.epfl.ch'] # must match integrations.gitlab.host
        # If your project is at https://gitlab.epfl.ch/rhdv-openshift/ocp-rhdh-project
        repoUrl: gitlab.epfl.ch?owner=rhdv-openshift&repo=ocp-rhdh-project
        title: "Provision project: ${{ parameters.project }}"
        description: "Namespace + RoleBindings for ${{ parameters.project }}"
        branchName: provision-${{ parameters.project }}
        targetBranch: main  # <-- set to your real default branch
        sourcePath: .
        targetPath: app-demo/${{ parameters.environment }} 

  output:
    links:
      - title: View MR
        url: ${{ steps.mr.output.remoteUrl }}