apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-template
  title: Project Request Template
  description: Project the Creation of an environment 
  tags:
    - recommended
    - environment
    - provisioning
spec:
  owner: service@example.com
  type: service

  parameters:
    - title: Environment Request
      required:
        - project
        - description
        - team
      properties:
        project:
          title: Project
          type: string
          description: Project or namespace that will contains ressources for the applications    
        description:
          title: Description
          type: string
          description: Short description for this environment                    
        team:
          title: Teams
          type: string
          description: Member of the project
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group

  steps:
    - id: template
      name: Code Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating: []
        values:
          description: ${{ parameters.description }}
          team: ${{ parameters.team.split("/")[1] }}
          project: ${{ parameters.project }}

    - id: pull-request
      name: make a pr with the new namespace
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=rhdh-demo&owner=josephassiga
        branchName: main
        title: ${{ parameters.project }} namespace
        description: This is a request for the creation of the ${{ parameters.project }}  from the ${{ parameters.team }} team
                               