---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-edit-${ t.group | replace('/', '-') | replace(' ', '-') | lower }}-rb
  namespace: developer
subjects:
  - kind: Group
    name: group-a
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
  ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-admin-${ t.group | replace('/', '-') | replace(' ', '-') | lower }}-rb
  namespace: developer
subjects:
  - kind: Group
    name: group-b
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
  ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-custom-${ t.group | replace('/', '-') | replace(' ', '-') | lower }}-rb
  namespace: developer
subjects:
  - kind: Group
    name: group-c
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-custom
  