
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airbus-demo-edit-group-a-rb
  namespace: airbus-demo
subjects:
  - kind: Group
    name: group-a
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io

  kind: ClusterRole
  name: edit


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airbus-demo-admin-group-b-rb
  namespace: airbus-demo
subjects:
  - kind: Group
    name: group-b
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io

  kind: ClusterRole
  name: admin


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airbus-demo-custom-group-c-rb
  namespace: airbus-demo
subjects:
  - kind: Group
    name: group-c
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io

  kind: Role
  name: airbus-demo-custom

