
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-edit-group-a-rb
  namespace: developer
subjects:
  - kind: Group
    name: group-a
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io

  kind: ClusterRole
  name: edit


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-view-group-b-rb
  namespace: developer
subjects:
  - kind: Group
    name: group-b
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io

  kind: ClusterRole
  name: view

