apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ${{values.description}}
  labels:
    team: ${{values.teams}}
    environment: ${{values.environment}}
  name: ${{values.project}}